siteTitle: "Houtarou Oreki"
logoUrl: "https://github.com/ewgsta.png"
logoText: "Houtarou Oreki"
footerText: "© 2026 Houtarou Oreki. All rights reserved."
heroTitle: "Houtarou Oreki"
quoteText: "What is meant to be will be, what is not meant to be should not be forced."
findMeOnLabel: "Find me on"
projectsLabel: "Projects"
postsLabel: "Posts"
readMoreLabel: "Read More"
viewAllProjectsLabel: "View All Projects"
viewAllPostsLabel: "View All Posts"
links:
  - platform: "fa-brands fa-github"
    url: "https://github.com/ewgsta"
  - platform: "fa-brands fa-x-twitter"
    url: "https://twitter.com/ewgsta"
