postsLabel: Posts
backToPostsLabel: ← Back to Posts
siteTitle: Furkan (ewgsta)
siteDescription: >-
  Software Engineer developer and open-source enthusiast. Explore my projects, blog
  posts, and more.
siteUrl: https://www.ewgsta.me
siteLanguage: en
siteAuthor: Furkan Can K.
siteKeywords: >-
  software, full-stack, developer, software engineer, web development, frontend, backend,
  programming, coding, blog, portfolio, software, javascript, typescript, react,
  nodejs, rust, go, ruby
ogImage: https://avatars.githubusercontent.com/u/159681870
logoUrl: https://avatars.githubusercontent.com/u/159681870
logoText: ''
footerText: '© 2026 - All rights reserved.'
heroTitle: Furkan :3
quoteText: "I'm a Software Engineer who develops open-source software."
findMeOnLabel: Find me on
projectsLabel: Projects
readMoreLabel: Read more
viewAllProjectsLabel: View all projects
viewAllPostsLabel: View all posts
postsSlug: posts
projectsSlug: projects
searchPlaceholder: Search
searchNoResults: 'No results were found: "{query}".'
searchEmptyState: Type to search
backToHomeLabel: ← Back to Home
backToProjectsLabel: ← Back to Projects
mail: hello@ewgsta.me
links:
  - platform: fa-brands fa-github
    url: https://github.com/ewgsta
    priority: 100
  - platform: fa-brands fa-bluesky
    url: https://bsky.app/profile/ewgsta.bsky.social
    priority: 70
  - platform: fa-brands fa-dev
    url: https://dev.to/ewgsta
    priority: 80
  - platform: fa-brands fa-reddit
    url: https://www.reddit.com/user/ewgsta/
    priority: 30
  - platform: fa-brands fa-discord
    url: https://discord.com/users/752050889958883380
    priority: 20
  - platform: fa-solid fa-envelope
    url: '#'
    priority: 90
